e-commerce/e-commerce/Controllers/AdminCategoryController.cs
using e_commerce.DAL;
using e_commerce.Models;
using e_commerce.Repository;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace e_commerce.Controllers
{
    [Authorize]
    public class AdminCategoryController : Controller
    {
        SimplyShoppingEntities db = new SimplyShoppingEntities();
        // GET: AdminCategory
        public GenericUnitOfWork _uw = new GenericUnitOfWork();
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryDetail categoryDetail)
        {
            try
            {
                var tbl_category = new Tbl_Category();
                tbl_category.CategoryName = categoryDetail.CategoryName;
                tbl_category.IsActive = true;
                tbl_category.IsDelete = false;
                db.Tbl_Category.Add(tbl_category);
                db.SaveChanges();
            }
            catch(Exception ex)
            {

            }
            //_uw.GetRepositoryInstance<Tbl_Category>().Add(tbl_category);
            return RedirectToAction("Categories", "Admin");
        }

        public ActionResult Edit(int id)
        {
            Tbl_Category  tbl_Category = db.Tbl_Category.Find(id);
            if (tbl_Category == null )
            {
                return HttpNotFound();
            }
            return View(tbl_Category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tbl_Category tbl_Category)
        {
            Tbl_Category olddata = db.Tbl_Category.Find(tbl_Category.CategoryId);
            if(olddata == null)
            {
                return HttpNotFound();
            }
            olddata.CategoryName = tbl_Category.CategoryName;
            if(tbl_Category.IsActive == null)
            {
                olddata.IsActive = false;
            }
            else
            {
                olddata.IsActive = tbl_Category.IsActive;
            }
            olddata.IsDelete = false;
            db.Entry(olddata).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Categories", "Admin");
        }
        public ActionResult Delete(int id)
        {
            Tbl_Category data = db.Tbl_Category.Find(id);
            return View(data);
        }
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_Category olddata = db.Tbl_Category.Find(id);
            olddata.IsDelete = true;
            olddata.IsActive = false;
            db.Entry(olddata).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction ("Categories","Admin");
        }
    }
}

e-commerce/e-commerce/Controllers/AdminController.cs
using e_commerce.DAL;
using e_commerce.Helpers;
using e_commerce.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace e_commerce.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        // GET: Admin
        public GenericUnitOfWork _uw = new GenericUnitOfWork();
        SimplyShoppingEntities db = new SimplyShoppingEntities();
        public ActionResult Dashboard()
        {
            DateTime prevMonth = DateTime.Now.AddMonths(-1);
            DateTime prevYear = DateTime.Now.AddYears(-1);
            var totalMonthSales = db.tbl_OrdKey.Where(x => x.PaymentType != (byte)EnumPaymentType.NotPaid).Where(x => x.OrdDate.Value.Year == DateTime.Now.Year && x.OrdDate.Value.Month == DateTime.Now.Month).Sum(x => x.OrdTot);
            var totalPreMonthSales = db.tbl_OrdKey.Where(x => x.PaymentType != (byte)EnumPaymentType.NotPaid).Where(x => x.OrdDate.Value.Year == prevYear.Year && x.OrdDate.Value.Month == prevMonth.Month).Sum(x => x.OrdTot);
            var totalYearlySales = db.tbl_OrdKey.Where(x => x.PaymentType != (byte)EnumPaymentType.NotPaid).Where(x => x.OrdDate.Value.Year == DateTime.Now.Year).Sum(x => x.OrdTot);
            var totalPrevYearlySales= db.tbl_OrdKey.Where(x => x.PaymentType != (byte)EnumPaymentType.NotPaid).Where(x => x.OrdDate.Value.Year == prevYear.Year).Sum(x => x.OrdTot);
            ViewBag.CurrentYearlyTotalSales = totalYearlySales;
            ViewBag.PreviousYearlyTotalSales = totalPrevYearlySales;
            ViewBag.CurrentMonthTotalSale = totalMonthSales;
            ViewBag.PreviousMonthTotalSale = totalPreMonthSales;
            return View();
        }
        public ActionResult Categories()
        {
            List<Tbl_Category> allCategory = _uw.GetRepositoryInstance<Tbl_Category>().GetAllRecordsIQueryable().Where(x =>x.IsDelete == false).ToList();
            return View(allCategory);
        }
    }
}

e-commerce/e-commerce/Controllers/UsersController.cs
using e_commerce.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace e_commerce.Controllers
{
    public class UsersController : Controller
    {
        SimplyShoppingEntities db = new SimplyShoppingEntities();
        // GET: Users
        public ActionResult Index()
        {
            List<Tbl_Users> list = db.Tbl_Users.ToList();
            return View(list);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tbl_Users tbl_Users)
        {
            tbl_Users.created_on = DateTime.Now;
            tbl_Users.status = true;
            db.Tbl_Users.Add(tbl_Users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            Tbl_Users data = db.Tbl_Users.Find(id);
            return View(data);
        }
    }
}

e-commerce/e-commerce/Views/Users/Create.cshtml
@model e_commerce.DAL.Tbl_Users
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Category</h1>
    <a href="@Url.Action("Categories","Admin")" class="d-sm-inline-block btn btn-sm btn-primary ">
        <i class="fas  text-white-50"></i> Back
    </a>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Add New Category</h6>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Create", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            @Html.AntiForgeryToken()
            <div class="row form-group">
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">First Name:</label>
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.firstname, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Last Name:</label>
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.lastname, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="row form-group">
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Email:</label>
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.email, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Password:</label>
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.password, new { @class = "form-control", required = "required", @type = "password", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="row form-group">
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Address:</label>
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.address, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Contact:</label>
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.contact_info, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                    <input  type="checkbox" data-toggle="toggle" data-offset="No" data-onSet="Yes" data-onStyle="success" data-offStyle="danger" />
                    @Html.ValidationMessageFor(model => model.contact_info, "", new { @class = "text-danger" })
                </div>

            </div>
            <a onclick="window.history.back()" class="btn btn-danger">Cancel</a>
            <input type="submit" class="btn btn-success" value="Save" />
        }

    </div>
</div>

e-commerce/e-commerce/Views/Users/Edit.cshtml
@model e_commerce.DAL.Tbl_Users
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Category</h1>
    <a href="@Url.Action("Index","Users")" class="d-sm-inline-block btn btn-sm btn-primary ">
        <i class="fas  text-white-50"></i> Back
    </a>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Add New Category</h6>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Edit", "Users", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            @Html.AntiForgeryToken()
            <div class="row form-group">
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">First Name:</label>
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.firstname, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Last Name:</label>
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.lastname, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="row form-group">
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Email:</label>
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.email, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Password:</label>
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.password, new { @class = "form-control", required = "required", @type = "password", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="row form-group">
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Address:</label>
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.address, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Contact:</label>
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.contact_info, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                    <input type="checkbox" data-toggle="toggle" data-offset="No" data-onSet="Yes" data-onStyle="success" data-offStyle="danger" />
                    @Html.ValidationMessageFor(model => model.contact_info, "", new { @class = "text-danger" })
                </div>

            </div>
            <a onclick="window.history.back()" class="btn btn-danger">Cancel</a>
            <input type="submit" class="btn btn-success" value="Save" />
        }

    </div>
</div>

e-commerce/e-commerce/Views/Users/Index.cshtml
@model List<e_commerce.DAL.Tbl_Users>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Users</h1>
    <a href="@Url.Action("Create","AdminCategory")" class="d-sm-inline-block btn btn-sm btn-primary ">
        <i class="fas fa-plus text-white-50"></i> Add
    </a>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">List</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Sr. No.</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Address</th>
                        <th>Contact</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>@(Model.IndexOf(item) + 1)</td>
                            <td>@item.firstname @item.lastname</td>
                            <td>
                                @item.email
                            </td>
                            <td>@item.address</td>
                            <td>@item.contact_info </td>
                            <td>
                                @if(item.status == true)
                                {
                                    <span class=" btn btn-success">Active</span>
                                }
                                else
                                {
                                    <span class="btn btn-danger">In-Active</span>
                                }
                            </td>
                            <td><a href="@Url.Action("Edit","AdminCategory",new { id= item.id})">Edit</a>|<a href="@Url.Action("Delete","AdminCategory",new { id= item.id})" style="color:red;">Delete</a></td>


                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>