e-commerce/e-commerce/Models/ChangePassword.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace e_commerce.Models
{
    public class ChangePassword
    {
        public string OldPassword { get; set; }
        public string NewPassword { get; set; }
        public string ConfirmPassword { get; set; }
    }
}

e-commerce/e-commerce/Controllers/AdminAccountController.cs
using e_commerce.DAL;
using e_commerce.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace e_commerce.Controllers
{
    public class AdminAccountController : Controller
    {
        SimplyShoppingEntities db = new SimplyShoppingEntities();
        // GET: AdminAccount
        public ActionResult login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Tbl_Users user)
        {
            bool isValid = db.Tbl_Users.Any(x => x.email == user.email && x.password == user.password);
            if (isValid)
            {
                FormsAuthentication.SetAuthCookie(user.email, false);
                return RedirectToAction("Dashboard", "Admin");
            }
            else
            {
                ModelState.AddModelError("", "Invalid Username and Password");
                return View();
            }   
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(ChangePassword changePassword)
        {
            try
            {
                if(changePassword!= null)
                {
                    var email = User.Identity.Name;
                    Tbl_Users tbl_Users = db.Tbl_Users.Where(x => x.email == email).FirstOrDefault();
                    if(changePassword.NewPassword == null || changePassword.OldPassword == null || changePassword.ConfirmPassword== null)
                    {
                        ModelState.AddModelError("", "Please add all details");
                        return View();
                    }
                    else if(changePassword.OldPassword != tbl_Users.password)
                    {
                        ModelState.AddModelError("", "Old password Doesn't match with user email");
                        return View();
                    }
                    else if(changePassword.NewPassword != changePassword.ConfirmPassword)
                    {
                        ModelState.AddModelError("", "New Password and Confirm password Doesnt match !");
                        return View();
                    }
                    else
                    {
                        tbl_Users.password = changePassword.ConfirmPassword;
                        db.Entry(tbl_Users).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                        ViewData["Message"] = "Success";
                        return View();
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Some error occured! Please try again.");
                    return View();
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.ToString());
                return View();
            }
        }
    }
}

e-commerce/e-commerce/Views/AdminAccount/ChangePassword.cshtml
@model e_commerce.Models.ChangePassword
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Category</h1>
    <a href="@Url.Action("Categories","Admin")" class="d-sm-inline-block btn btn-sm btn-primary ">
        <i class="fas  text-white-50"></i> Back
    </a>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        @*<h6 class="m-0 font-weight-bold text-primary">Add New Category</h6>*@
    </div>
    <div class="card-body">
        @using (Html.BeginForm("ChangePassword", "AdminAccount", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            if(ViewData["Message"] != null)
            {
                <div class="alert alert-success">Password Changes Successfully</div>
            }
            <div class="row form-group">
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Old Password</label>
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.OldPassword, new { @class = "form-control",@type="password", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.OldPassword, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">New Password:</label>
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.NewPassword, new { @class = "form-control", @type = "password", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="row form-group">
                <div class="col-md-2">
                    <label class="control-label" style="margin-top:5px;">Confirm Password:</label>
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(model => model.ConfirmPassword, new { @class = "form-control", @type = "password", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
               

            </div>
            
            <a onclick="window.history.back()" class="btn btn-danger">Cancel</a>
            <input type="submit" class="btn btn-success" value="Save" />
        }

    </div>
</div>

e-commerce/e-commerce/Views/AdminAccount/Login.cshtml
@model e_commerce.DAL.Tbl_Users
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="@Url.Content("~/Content/bower_components/bootstrap/dist/css/bootstrap.min.css")">
    <!-- DataTables -->
    <link rel="stylesheet" href="@Url.Content("~/Content/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css")">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="@Url.Content("~/Content/bower_components/font-awesome/css/font-awesome.min.css")">
    <!-- Theme style -->
    <link rel="stylesheet" href="@Url.Content("~/Content/dist/css/AdminLTE.min.css")">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="dist/css/skins/_all-skins.min.css">
    <!-- Magnify -->
    <link rel="stylesheet" href="magnify/magnify.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- Paypal Express -->
    <script src="https://www.paypalobjects.com/api/checkout.js"></script>
    <!-- Google Recaptcha -->
    <script src='https://www.google.com/recaptcha/api.js'></script>

    <!-- Custom CSS -->
</head>
<body class=" hold-transition login-page">
    <div class="login-box">
        <div class="login-box-body">
            <p class="login-box-msg">Sign in </p>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group has-feedback">
                    <input type="email" class="form-control" name="email" placeholder="Email" required>
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" name="Password" placeholder="Password" required>
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat" name="login"><i class="fa fa-sign-in"></i> Sign In</button>
                    </div>
                </div>
            }
            <br>
            <a href="password_forgot.php">I forgot my password</a><br>
            <a href="signup.php" class="text-center">Register a new membership</a><br>
            <a href="@Url.Action("Index","Home")"><i class="fa fa-home"></i> Home</a>
        </div>
    </div>
    <!-- jQuery 3 -->
    <script src="@Url.Content("~/Content/bower_components/jquery/dist/jquery.min.js")"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="@Url.Content("~/Content/bower_components/bootstrap/dist/js/bootstrap.min.js")"></script>
    <!-- DataTables -->
    <script src="@Url.Content("~/Content/bower_components/datatables.net/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Content/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js")"></script>
    <!-- SlimScroll -->
    <script src="@Url.Content("~/Content/bower_components/jquery-slimscroll/jquery.slimscroll.min.js")"></script>
    <!-- FastClick -->
    <script src="@Url.Content("~/Content/bower_components/fastclick/lib/fastclick.js")"></script>
    <!-- AdminLTE App -->
    <script src="@Url.Content("~/Content/dist/js/adminlte.min.js")"></script>
    <!-- CK Editor -->
    <script src="@Url.Content("~/Content/bower_components/ckeditor/ckeditor.js")"></script>
</body>
</html>