e-commerce/e-commerce/Models/Home/Item.cs
using e_commerce.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace e_commerce.Models.Home
{
    public class Item
    {
        public Tbl_Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

e-commerce/e-commerce/Controllers/HomeController.cs
using e_commerce.DAL;
using e_commerce.Models.Home;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace e_commerce.Controllers
{
    public class HomeController : Controller
    {
        SimplyShoppingEntities db = new SimplyShoppingEntities();
        public ActionResult Index(string Search,int? page)
        {
            HomeIndexViewModel model = new HomeIndexViewModel();
            return View(model.CreateModel(Search,page));
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult AddToCart(int productId)
        {
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                var product = db.Tbl_Product.Find(productId);
                cart.Add(new Item()
                {
                    Product = product,
                    Quantity = 1
                });
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                List<Item> newcart = new List<Item>();
                var product = db.Tbl_Product.Find(productId);
                var i = 0;
                foreach (var item in cart)
                {
                    if (item.Product.ProductId == productId)
                    {
                        int prevQty = item.Quantity;
                        //cart.Remove(item);
                        newcart.Add(new Item()
                        {
                            Product = product,
                            Quantity = prevQty + 1
                        });
                        i = i + 1;
                    }
                    else
                    {
                        newcart.Add(new Item()
                        {
                            Product = item.Product,
                            Quantity = item.Quantity
                        });
                    }
                }
                if (i==0)
                {
                    newcart.Add(new Item()
                    {
                        Product = product,
                        Quantity = 1
                    });
                }
                Session["cart"] = newcart;
            }
            return Redirect("Index");
        }
        public ActionResult RemoveFromCart(int productId)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            foreach (var item in cart)
            {
                if (item.Product.ProductId == productId)
                {
                    cart.Remove(item);
                    break;
                }
            }
            Session["cart"] = cart;
            return Redirect("Index");
        }

        public ActionResult Checkout()
        {
            return View();
        }

        public ActionResult CheckoutDetails()
        {
            return View();
        }

        public ActionResult Updatecart(int productId,int mthd)
        {
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                var product = db.Tbl_Product.Find(productId);
                cart.Add(new Item()
                {
                    Product = product,
                    Quantity = 1
                });
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                List<Item> newcart = new List<Item>();
                var product = db.Tbl_Product.Find(productId);
                var i = 0;
                foreach (var item in cart)
                {
                    if (item.Product.ProductId == productId)
                    {
                        int prevQty = item.Quantity;
                        //cart.Remove(item);
                        if(mthd ==1)
                        {
                            newcart.Add(new Item()
                            {
                                Product = product,
                                Quantity = prevQty + 1
                            });
                        }
                        else
                        {
                            if(prevQty >1)
                            {
                                newcart.Add(new Item()
                                {
                                    Product = product,
                                    Quantity = prevQty -1
                                });
                            }
                        }
                        
                    }
                    else
                    {
                        newcart.Add(new Item()
                        {
                            Product = item.Product,
                            Quantity = item.Quantity
                        });
                    }
                }
               
                Session["cart"] = newcart;
            }
            
            return RedirectToAction("Checkout", "Home");
        }
        [ChildActionOnly]
        public ActionResult CategoryList()
        {
            var catList = db.Tbl_Category.Where(x=>x.IsActive == true && x.IsDelete== false).ToList();
            return PartialView(catList);
        }

        public ActionResult ShippingDetails()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShippingDetails(Tbl_ShippingDetails tbl_ShippingDetails)
        {
            Session["ShippingDetails"] = tbl_ShippingDetails;
            return View();
        }
    }
}

e-commerce/e-commerce/Controllers/PaymentController.cs
using e_commerce.DAL;
using e_commerce.Helpers;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace e_commerce.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment

        SimplyShoppingEntities db = new SimplyShoppingEntities();
        public ActionResult PaymentWithPaypal(string Cancel = null)
        {
            //getting the apiContext
            APIContext apiContext = PaypalConfiguration.GetAPIContext();

            try
            {
                //A resource representing a Payer that funds a payment Payment Method as paypal
                //Payer Id will be returned when payment proceeds or click to pay
                string payerId = Request.Params["PayerID"];

                if (string.IsNullOrEmpty(payerId))
                {
                    //this section will be executed first because PayerID doesn't exist
                    //it is returned by the create function call of the payment class

                    // Creating a payment
                    // baseURL is the url on which paypal sendsback the data.
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority +
                                "/Payment/PaymentWithPayPal?";

                    //here we are generating guid for storing the paymentID received in session
                    //which will be used in the payment execution

                    var guid = Convert.ToString((new Random()).Next(100000));

                    //CreatePayment function gives us the payment approval url
                    //on which payer is redirected for paypal account payment

                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid);

                    //get links returned from paypal in response to Create function call

                    var links = createdPayment.links.GetEnumerator();

                    string paypalRedirectUrl = null;

                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;

                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment
                            paypalRedirectUrl = lnk.href;
                        }
                    }

                    // saving the paymentID in the key guid
                    Session.Add(guid, createdPayment.id);

                    return Redirect(paypalRedirectUrl);
                }
                else
                {

                    // This function exectues after receving all parameters for the payment

                    var guid = Request.Params["guid"];

                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);

                    //If executed payment failed then we will show payment failure message to user
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("FailureView");
                    }
                }
            }
            catch (Exception ex)
            {
                return View("FailureView");
            }

            //on successful payment, show success page to user.
            return RedirectToAction("SuccessView");
        }

        private PayPal.Api.Payment payment;
        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution() { payer_id = payerId };
            this.payment = new Payment() { id = paymentId };
            return this.payment.Execute(apiContext, paymentExecution);
        }

        private Payment CreatePayment(APIContext apiContext, string redirectUrl)
        {

            //create itemlist and add item objects to it
            var itemList = new ItemList() { items = new List<Item>() };

            //Adding Item Details like name, currency, price etc
            List<Models.Home.Item> cart = (List<Models.Home.Item>)(Session["cart"]);
            foreach (var item in cart )
            {
                itemList.items.Add(new Item()
                {
                    name = item.Product.ProductName.ToString(),
                    currency = "USD",
                    price = item.Product.Price.ToString(),
                    quantity = item.Quantity.ToString(),
                    sku = "sku"
                });
            }
            

            var payer = new Payer() { payment_method = "paypal" };

            // Configure Redirect Urls here with RedirectUrls object
            var redirUrls = new RedirectUrls()
            {
                cancel_url = redirectUrl + "&Cancel=true",
                return_url = redirectUrl
            };

            // Adding Tax, shipping and Subtotal details
            var details = new Details()
            {
                tax = "0",
                shipping = "0",
                subtotal = Session["SessTotal"].ToString()
            };

            //Final amount with details
            var amount = new Amount()
            {
                currency = "USD",
                total = Session["SessTotal"].ToString(), // Total must be equal to sum of tax, shipping and subtotal.
                details = details
            };
            var invoice = Convert.ToString((new Random()).Next(100000));
             invoice = "#" + invoice.ToString();
            var transactionList = new List<Transaction>();
            // Adding description about the transaction
            transactionList.Add(new Transaction()
            {
                description = "Transaction description",
                invoice_number = invoice , //Generate an Invoice No
                amount = amount,
                item_list = itemList
            });


            this.payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = transactionList,
                redirect_urls = redirUrls
            };

            // Create a payment using a APIContext
            return this.payment.Create(apiContext);
        }
        public ActionResult SuccessView()
        {
            try
            {
                List<Models.Home.Item> cart = (List<Models.Home.Item>)(Session["cart"]);
                tbl_OrdKey ordkey = new tbl_OrdKey();
                Tbl_Members member =(Tbl_Members)(Session["UserName"]);
                ordkey.CustName = member.FristName + " "+member.LastName;
                ordkey.CustPhone = member.contact;
                ordkey.OrdDate = DateTime.Now;
                ordkey.IsDelivered = false;
                ordkey.PaymentType = (byte)EnumPaymentType.Paypal;
                ordkey.OrdTot = Convert.ToDecimal(Session["SessTotal"].ToString());
                db.tbl_OrdKey.Add(ordkey);
                db.SaveChanges();
                var ordid = db.tbl_OrdKey.OrderByDescending(x=>x.OrdID).ToList();
                var id = ordid.FirstOrDefault().OrdID;
                foreach (var item in cart)
                {
                    tbl_OrdHolder ordHolder = new tbl_OrdHolder();
                    ordHolder.ItemType = item.Product.ProductName;
                    ordHolder.ItemDescription = "";
                    ordHolder.Price = item.Product.Price* item.Quantity;
                    ordHolder.Quantity = item.Quantity;
                    ordHolder.OrdId = Convert.ToInt64(id);
                    db.tbl_OrdHolder.Add(ordHolder);
                    //db.SaveChanges();
                }
                db.SaveChanges();
                Tbl_ShippingDetails det = (Tbl_ShippingDetails)(Session["ShippingDetails"]);
                Tbl_ShippingDetails temp = new Tbl_ShippingDetails();
                temp.Adress = det.Adress;
                temp.City = det.City;
                temp.Country = det.Country;
                temp.State = det.State;
                temp.ZipCode = det.ZipCode;
                temp.AmountPaid = Convert.ToDecimal(Session["SessTotal"].ToString());
                temp.PaymentType = "PayPal";
                temp.MemberId = member.MemberId;
                temp.OrdId = id;
                db.Tbl_ShippingDetails.Add(temp);
                db.SaveChanges();
                Session.Remove("cart");
                Session.Remove("ShippingDetails");
            }
            catch(Exception ex)
            {

            }
            return View();
        }
    }
}

e-commerce/e-commerce/Controllers/ProductController.cs
using e_commerce.DAL;
using e_commerce.Models.Home;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace e_commerce.Controllers
{
    public class ProductController : Controller
    {
        SimplyShoppingEntities db = new SimplyShoppingEntities();
        // GET: Product
        public ActionResult ProductList(int? CategoryId)
        {
            var productlist = db.Tbl_Product.Where(x => x.CategoryId == CategoryId).ToList();
            return View(productlist);
        }
        public ActionResult Product(int id)
        {
            Tbl_Product tbl_Product = db.Tbl_Product.Find(id);
            Tbl_Category dt = db.Tbl_Category.Find(tbl_Product.CategoryId);
            ViewBag.category = dt.CategoryName;
            Item item = new Item();
            item.Product = tbl_Product;
            return View(item);
        }
        public ActionResult AddToCart(Item item)
        {
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                var product = db.Tbl_Product.Find(item.Product.ProductId);
                cart.Add(new Item()
                {
                    Product = product,
                    Quantity = item.Quantity
                });
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                List<Item> newcart = new List<Item>();
                var product = db.Tbl_Product.Find(item.Product.ProductId);
                var i = 0;
                foreach (var data in cart)
                {
                    if (data.Product.ProductId == item.Product.ProductId)
                    {
                        int prevQty = data.Quantity;
                        //cart.Remove(item);
                        newcart.Add(new Item()
                        {
                            Product = product,
                            Quantity = prevQty + item.Quantity
                        });
                        i = i + 1;
                    }
                    else
                    {
                        newcart.Add(new Item()
                        {
                            Product = data.Product,
                            Quantity = data.Quantity
                        });
                    }
                }
                if (i == 0)
                {
                    newcart.Add(new Item()
                    {
                        Product = product,
                        Quantity = item.Quantity
                    });
                }
                Session["cart"] = newcart;
            }
            return RedirectToAction("Index","Home");
        }
    }
}

e-commerce/e-commerce/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

e-commerce/e-commerce/Views/Home/CategoryList.cshtml
@model IEnumerable<e_commerce.DAL.Tbl_Category>
@{
    foreach (var item in Model)
    {
        <li>
            <a href="@Url.Action("ProductList","Product",new { CategoryId=item.CategoryId})" )">@item.CategoryName</a>
        </li>
    }
}

e-commerce/e-commerce/Views/Home/Checkout.cshtml
@using e_commerce.Models.Home;
@{
    ViewBag.Title = "Checkout";
}

<h2>Your Cart</h2>
@if (Session["cart"] == null)
{
    <div class="alert alert-danger">
        <strong>No product added to cart!</strong>
    </div>

}
else
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total Price</th>
                <th>Add</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Item item in (List<Item>)Session["cart"])
            {
                decimal?  i = 0;
                i = item.Product.Price * Convert.ToDecimal(item.Quantity);
                <tr>
                    <td>@item.Product.ProductName</td>
                    <td>$ @item.Product.Price</td>
                    <td>@item.Quantity</td>
                    <td>$ @i</td>
                    <td>
                        <a href="@Url.Action("Updatecart", "Home", new { productId = item.Product.ProductId, mthd=1})">
                            <i class="fa fa-plus"></i>
                        </a>
                        <a href="@Url.Action("Updatecart", "Home", new { productId = item.Product.ProductId,mthd=0 })">
                            <i class="fa fa-minus"></i>
                        </a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
    <a class="btn btn-success" href="@Url.Action("CheckoutDetails","Home")">Checkout >></a>

}

e-commerce/e-commerce/Views/Home/CheckoutDetails.cshtml
@using e_commerce.Models.Home;
@{
    ViewBag.Title = "CheckoutDetails";
}

@if (Session["cart"] == null)
{
    <div class="alert alert-danger">
        <strong>No product added to cart!</strong>
    </div>

}
else
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Line Total</th>

            </tr>
        </thead>
        <tbody>
            @{
                int Total = 0;
            }
            @foreach (Item item in (List<Item>)Session["cart"])
            {
                int lineTotal = Convert.ToInt32(item.Quantity * item.Product.Price);
                Total = Convert.ToInt32(@Total + lineTotal);
                Session["SessTotal"] = Total;
                <tr>
                    <td>@item.Product.ProductName</td>
                    <td>@item.Product.Price</td>
                    <td>@item.Quantity</td>
                    <td>$@lineTotal</td>
                </tr>
            }

            <tr>
                <td colspan="4" class="text-right"><b>Total:$ @Total</b></td>
            </tr>
        </tbody>
    </table>
    if (Session["UserName"] != null)
    {
        <a href="@Url.Action("PaymentWithPaypal", "Payment")" class="btn btn-success">Payment >></a>
    }
    else
    {
        <a href="@Url.Action("Login","Account")" class="btn btn-success">Sign In to Continue</a>
    }

}

e-commerce/e-commerce/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

e-commerce/e-commerce/Views/Home/Index.cshtml
@model e_commerce.Models.Home.HomeIndexViewModel
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Home Page";
}

<div id="themeSlider" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#themeSlider" data-slide-to="0" class="active"></li>
        <li data-target="#themeSlider" data-slide-to="1"></li>
        <li data-target="#themeSlider" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <div class="imgOverlay"></div>
            <img style="height:320px;width:100%" src="@Url.Content("~/Images/Banner1.jpg")" alt="First slide">
            <div class="carousel-caption">
                <h3>New</h3>

            </div>
        </div>
        <div class="item">
            <div class="imgOverlay"></div>
            <img style="height:320px;width:100%" src="@Url.Content("~/Images/Banner2.jpg")" alt="Second slide">
            <div class="carousel-caption">
                <h3>My home Appliance</h3>

            </div>
        </div>
        <div class="item">
            <div class="imgOverlay"></div>
            <img style="height:320px;width:100%" src="@Url.Content("~/Images/Banner3.jpg")" alt="Third slide">
            <div class="carousel-caption">
                <h3>Stay Home, Stay Safe</h3>
                <h5>Order Online</h5>

            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#themeSlider" data-slide="prev">
        <span class="fa fa-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#themeSlider" data-slide="next">
        <span class="fa fa-chevron-right"></span>
    </a>

</div>
<div class="olContent f1"><h2 style="color:black">Search Product/Category</h2></div>
<form method="post">
    <div class="olSearch fr">
        <input type="text" placeholder="Enter Keyword" name="Search" class="inputComn houseText form-control" />
        <div class="searchIcon">
            <button type="submit" class="searchBtn">
                <img height="45px" width="45px" src="@Url.Content("~/Images/Search-var-flat.png")" />
            </button>
        </div>
    </div>
</form>


<div class="row">
    <div class="col-md-12">
        <div class="page-header">
            <h2>Our Producrs <small>trends products</small></h2>
        </div>
    </div>
</div>

<div class="row product-container">
    @if (Model != null)
    {
        foreach (var item in Model.listofProducts)
        {
            <div class="col-md-3 col-sm-3 col-xs-6" style="margin-bottom:8px">
                <div class="thumbnail product-item" style="height:300px">
                    <a href="@Url.Action("Product","Product",new { id=item.ProductId})">
                        <img class="img-responsive" title="Click to View Product detail"
                             style="cursor:pointer;height:160px;width:100%"
                             src="@Url.Content("~/Images/"+item.ProductImage)" />
                    </a>


                    <div class="caption">
                        <h5> @item.ProductName</h5>
                        <p>$ @item.Price</p>
                        <p>
                            <a href="@Url.Action("Product","Product",new { id=item.ProductId})">
                                @if (item.Quantity > 0)
                                {
                                    using (Html.BeginForm("AddToCart", "Home", new { productId = item.ProductId }, FormMethod.Post))
                                    {
                                        <button class="pull-right" type="submit"><i class="fa fa-shopping-cart pull-right"></i></button>
                                    }
                                    <span class="btn btn-success">Available</span>
                                }
                                else
                                {
                                    <span class="btn btn-danger">Not Available</span>
                                }
                            </a>
                        </p>
                        @if (item.IsFeatured == true)
                        {
                            <div class="product-item-badge">Featured</div>
                        }
                    </div>
                </div>
            </div>
        }
    }
</div>
<div class="container" style="text-align:center">
    @Html.PagedListPager(Model.listofProducts, page => Url.Action("Index", new { page, search = Request.QueryString["search"] }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayItemSliceAndTotal = true })
</div>

e-commerce/e-commerce/Views/Home/ShippingDetails.cshtml
@model e_commerce.DAL.Tbl_ShippingDetails
@{
    ViewBag.Title = "ShippingDetails";
}

<div>
    @using (Html.BeginForm("ShippingDetails", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken();
        <div class="row form-group">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Adress, "Address")
            </div>
            <div class="col-md-8">
                @Html.TextBoxFor(model => model.Adress, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-4">
                @Html.LabelFor(model => model.City, "City")
            </div>
            <div class="col-md-8">
                @Html.TextBoxFor(model => model.City, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-4">
                @Html.LabelFor(model => model.ZipCode, "ZipCode")
            </div>
            <div class="col-md-8">
                @Html.TextBoxFor(model => model.ZipCode, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-4">
                @Html.LabelFor(model => model.State, "State")
            </div>
            <div class="col-md-8">
                @Html.TextBoxFor(model => model.State, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-4">
                @Html.LabelFor(model => model.Country, "Country")
            </div>
            <div class="col-md-8">
                @Html.TextBoxFor(model => model.Country, new { @class = "form-control", required = "required", autofocus = "autofocus" })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>
        <input type="submit" value="Submit" class="btn">
    }
    </div>